In [1]:
import numpy as np
import pandas as pd
import sklearn
import tensorflow as tf
import matplotlib.pyplot as plt

# Check for TensorFlow GPU access
print(f"TensorFlow has access to the following devices:\n{tf.config.list_physical_devices()}")

# See TensorFlow version
print(f"TensorFlow version: {tf.__version__}")

TensorFlow has access to the following devices:
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
TensorFlow version: 2.15.0


In [2]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")

# Check PyTorch has access to MPS (Metal Performance Shader, Apple's GPU architecture)
print(f"Is MPS (Metal Performance Shader) built? {torch.backends.mps.is_built()}")
print(f"Is MPS available? {torch.backends.mps.is_available()}")

# Set the device      
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

PyTorch version: 2.2.1
Is MPS (Metal Performance Shader) built? True
Is MPS available? True
Using device: mps


In [3]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [4]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
len(tokenizer.word_index)

17

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [8]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [9]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [10]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

2024-03-02 19:28:00.781992: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-03-02 19:28:00.782225: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-03-02 19:28:00.782252: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-03-02 19:28:00.782801: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-03-02 19:28:00.783345: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.compile('adam','accuracy')

In [12]:
pred = model.predict(sequences)
print(pred)

2024-03-02 19:28:20.859964: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 400ms/step
[[[ 0.02657313  0.02644023]
  [-0.0277      0.04073794]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]]

 [[-0.0277      0.04073794]
  [-0.0277      0.04073794]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]]

 [[-0.01346722 -0.03491588]
  [-0.01346722 -0.03491588]
  [ 0.01470181 -0.0440915 ]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]]

 [[-0.00070063  0.0416025 ]
  [ 0.03453759  0.04468593]
  [-0.00070063  0.0416025 ]
  [-0.0277      0.04073794]
  [-0.00070063  0.0416025 ]]

 [[-0.01659292  0.00109706]
  [-0.00295002  0.03893684]
  [-0.01912233  0.01516832]
  [-0.00764117 -0.00201256]
  [ 0.01103694 -0.00665421]]

 [[ 0.01584664  0.02085999]
  [ 0.01584664  0.02085999]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]
  [ 0.01103694 -0.00665421]]

 [[-0.02777669  0.0122112 ]
  [-0.02777669  0.0122112 ]
  [ 0.01103694 -0.00665421]
  [ 0.01103

In [13]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [14]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 6s 0us/step


In [15]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [16]:
X_train.shape

(25000, 50)

In [18]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 60s 73ms/step - loss: 0.5422 - acc: 0.7093 - val_loss: 0.4236 - val_acc: 0.8085
Epoch 2/5
782/782 [==============================] - 43s 55ms/step - loss: 0.3671 - acc: 0.8412 - val_loss: 0.4169 - val_acc: 0.8104
Epoch 3/5
782/782 [==============================] - 41s 52ms/step - loss: 0.3145 - acc: 0.8729 - val_loss: 0.4320 - val_acc: 0.8052
Epoch 4/5
782/782 [==============================] - 39s 50ms/step - loss: 0.2846 - acc: 0.8866 - val_loss: 0.4821 - val_acc: 0.8000
Epoch 5/5
782/782 [==============================] - 40s 51ms/step - loss: 0.2568 - acc: 0.9026 - val_loss: 0.5154 - val_acc: 0.7944
